

services:
  mcchappyr.translation.auto_adder:
    class: MyCrowdCompany\TranslationBundle\Translation\AutoAdder
    arguments: [ '@?translator.data_collector', '@mcchappyr.translation', '@mcchappyr.translation.filesystem' ]
    tags:
      - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate, priority: 10 }
